# Generated by Django 5.2 on 2026-05-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_athleteinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
