# Generated by Django 5.2 on 2026-09-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='run',
            field=models.IntegerField(),
        ),
    ]
