# Generated by Django 5.2 on 2026-09-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_alter_position_latitude_alter_position_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
